name: branch-name-must-start-with-jira-issue-id
on: pull_request

jobs:
  branch-name-must-start-with-jira-issue-id:
    runs-on: ubuntu-latest
    steps:
      - name: "Enforce branch name rules"
        uses: deepakputhraya/action-branch-name@master # https://github.com/marketplace/actions/branch-name-rules
        with:
          regex: '^BL-\d+-\S*$' # Regex the branch should match.
          # allowed_prefixes: 'feature,stable,fix' # All branches should start with the given prefix
          # ignore: master,develop # Ignore exactly matching branch names from convention
          # min_length: 5 # Min length of the branch name
          # max_length: 20 # Max length of the branch name
      - name: "Notify of errors"
        if: ${{ failure() }}
        run: echo "⚠️ IMPORTANT:Your branch name must start with a Jira issue ID! (e.g., BL-123)"
