name: enforce_branch_name_2

on: create

jobs:
  enforce_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
      - name: "Read CODEOWNERS file"
        id: getcodeowners
        run: echo "::set-output name=codeowners::$(cat {{ './CODEOWNERS' }})"
      - name: "Enforce convention if creator is not a CODEOWNER"
        if: '! contains(${{ steps.getcodeowners.outputs.codeowners }}, ${{ github.actor }})'
        run: REGEXP="^refs\/heads\/BL-\d+-\S*$" && BRANCH=${{ github.ref }} && [[ $BRANCH =~ $REGEXP ]] && exit 0
